stages:
  - build
  - test
  - deploy


build job:
  stage: build
  script:
    - echo "This is a first demo build job"

test job:
  stage: test
  script:
    - echo "This is a first demo test job"

deploy job:
  stage: deploy
  script:
    - echo "This is a first demo deploy job"